services:
  db:
    image: mysql:9.0.1
    container_name: laravel_db_repetirtarea
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: devtest
      TZ: Europe/Madrid
    volumes:
      - db_data_repetirtarea:/var/lib/mysql
    networks:
      - default
  
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app_repetirtarea
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
      - ./my-custom-000-default.conf:/etc/apache2/sites-available/000-default.conf
    ports:
      - "80:80"
      - "443:443"
      - "2222:22"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: laravel
      DB_PASSWORD: devtest
      XDEBUG_MODE: debug
      XDEBUG_CONFIG: client_host=host.docker.internal client_port=9003
      TZ: Europe/Madrid
    networks:
      - default
    extra_hosts:
      - "host.docker.internal:host-gateway"
  
  phpmyadmin:
    image: phpmyadmin:5.2.1
    container_name: laravel_phpmyadmin_repetirtarea
    depends_on:
      - db
    links: 
      - db:db
    ports:
      - "8000:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      TZ: Europe/Madrid

volumes:
  db_data_repetirtarea: